// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaWeb2_RicardoWehmuth.Context;

#nullable disable

namespace ProvaWeb2_RicardoWehmuth.Migrations
{
    [DbContext(typeof(ComandaContext))]
    partial class ComandaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Comanda", b =>
                {
                    b.HasOne("ProvaWeb2_RicardoWehmuth.Models.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Produto", b =>
                {
                    b.HasOne("ProvaWeb2_RicardoWehmuth.Models.Comanda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ComandaId");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Comanda", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ProvaWeb2_RicardoWehmuth.Models.Usuario", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
